"""AI banter for the group: a short scripted-style conversation between named
characters, posted by the single VYBLA bot as one formatted message — not
simulated separate Telegram accounts. This is a transparent content format
(like a mini comic strip/script), not an impersonation of real users:
Telegram already tags the poster as "bot", and the "X, Y и Z обсуждают"
framing makes clear it's an authored bit, not a live human conversation.

Two distinct models voice two character groups (not one model talking to
itself), each turn a separate live call so every persona's line is actually
generated by its assigned model, seeing the running transcript so far.
Falls back to a curated scripted bank on missing key, any API failure, or
unparsable/empty output — the feature never breaks the group.

Auto-throttle: once the group has real (non-bot) activity of its own (see
cache.bump_real_activity, wired from bot.py's moderate_group), posting here
backs off — see post_dialogue().
"""
import logging
import random
import re

import httpx
from aiogram import Bot

import binding
import cache
from config import (
    BOT_USERNAME, OPENROUTER_API_KEY, OPENROUTER_MODEL_FEMALE,
    OPENROUTER_MODEL_MALE, DIALOGUE_ACTIVITY_THRESHOLD,
)

log = logging.getLogger("vybla.dialogue")

# Reasoning-capable models (e.g. mimo-v2.5) spend part of the completion
# budget on an internal "reasoning" field before writing the final reply —
# too small a max_tokens returns empty content. 300 leaves enough headroom
# for both on every model tested, at negligible extra cost either way.
_MAX_TOKENS = 300

# Some models occasionally leak CJK characters into Russian output (seen
# live in testing, e.g. mimo-v2.5 once produced "автор最好的"). Treat a line
# with any CJK codepoint as a failed turn — it gets skipped like any other
# failure rather than posted with garbled text.
_FOREIGN_SCRIPT_RE = re.compile(r"[一-鿿぀-ヿ가-힯]")

# ~10 characters, each voiced by one of two models — genuinely two different
# models in conversation, not one model role-playing both sides.
PERSONAS = [
    {"name": "Ева",    "model": OPENROUTER_MODEL_FEMALE, "group": "f", "style": "наблюдательная, с лёгким сарказмом, топит за честность"},
    {"name": "Соня",   "model": OPENROUTER_MODEL_FEMALE, "group": "f", "style": "добрая, мягкая, всех поддерживает"},
    {"name": "Алина",  "model": OPENROUTER_MODEL_FEMALE, "group": "f", "style": "циничная, за словом в карман не лезет"},
    {"name": "Марго",  "model": OPENROUTER_MODEL_FEMALE, "group": "f", "style": "романтичная, верит в грин флаги и хороших людей"},
    {"name": "Ирина",  "model": OPENROUTER_MODEL_FEMALE, "group": "f", "style": "прямолинейная, режет правду-матку без прикрас"},
    {"name": "Макс",   "model": OPENROUTER_MODEL_MALE, "group": "m", "style": "эмоциональный, делится личным, немного наивный"},
    {"name": "Дан",    "model": OPENROUTER_MODEL_MALE, "group": "m", "style": "ироничный, любит подколоть, но не зло"},
    {"name": "Артём",  "model": OPENROUTER_MODEL_MALE, "group": "m", "style": "рассудительный, психолог-самоучка, всё раскладывает по полочкам"},
    {"name": "Женя",   "model": OPENROUTER_MODEL_MALE, "group": "m", "style": "застенчивый, часто сомневается вслух"},
    {"name": "Костя",  "model": OPENROUTER_MODEL_MALE, "group": "m", "style": "самоуверенный, любит поспорить"},
]

TOPICS = [
    "ред флаги в отношениях",
    "грин флаги, которые недооценивают",
    "получить анонимный комплимент от незнакомца",
    "признаться в чувствах анонимно",
    "смешная анонимка, которая оказалась правдой",
    "почему людям проще быть честными анонимно",
    "как понять, что тебе врут",
    "доверие в отношениях",
    "стоит ли писать бывшему(ей) анонимный вайб",
    "самый неожиданный комплимент, который можно получить",
]

_TURN_RULES = (
    "Правила: ОДНА короткая реплика, до 15 слов, разговорный русский, "
    "максимум 1 эмодзи, без ссылок, без реальных имён и данных людей, без "
    "мата и оскорблений, дружелюбно-подкалывающий тон. Это художественный "
    "диалог для развлечения, не утверждай, что это реальная переписка. "
    "Ответь ТОЛЬКО текстом реплики, без имени и без кавычек."
)

# Used when OPENROUTER_API_KEY is unset, every call fails, or output doesn't
# parse — the feature must never break the group.
_FALLBACK_DIALOGUES = [
    [("Ева", "чувак прислал мне «ты как дорогой парфюм» анонимно"),
     ("Макс", "это грин флаг или он просто начитался тик-тока?"),
     ("Ева", "не знаю, но приятно 🙂"),
     ("Макс", "мне вчера ред флаг пришёл: «ты слишком много думаешь»"),
     ("Ева", "это НЕ ред флаг, это же правда"),
     ("Макс", "вот именно поэтому я и обиделся")],
    [("Макс", "как думаешь, люди честнее анонимно или в лицо?"),
     ("Ева", "анонимно, стопроцентно"),
     ("Макс", "а если это просто повод быть грубым?"),
     ("Ева", "тогда это не честность, а трусость с эмодзи")],
    [("Алина", "мне кажется, ред флаги реально недооценивают"),
     ("Дан", "например?"),
     ("Алина", "когда человек никогда не признаёт свою неправоту"),
     ("Дан", "…я записываю"),
     ("Алина", "себе, надеюсь")],
    [("Костя", "получил анонимку «у тебя вайб дорогой бывшей»"),
     ("Соня", "это комплимент или диагноз?"),
     ("Костя", "я решил, что комплимент"),
     ("Соня", "здоровый подход, уважаю")],
    [("Марго", "грин флаг — это когда человек говорит «мне надо подумать»"),
     ("Артём", "а не сразу «да» или скандал?"),
     ("Марго", "именно"),
     ("Артём", "тогда я 70% грин флаг")],
    [("Женя", "стоит писать бывшей анонимный вайб?"),
     ("Ирина", "смотря что хочешь сказать"),
     ("Женя", "что-то доброе, честно"),
     ("Ирина", "тогда пиши. если хочешь уколоть — не надо")],
    [("Ева", "самое честное, что мне анонимно написали — «ты классный, но опаздываешь всегда»"),
     ("Дан", "жёстко"),
     ("Ева", "зато правда"),
     ("Дан", "правда обычно и жёсткая")],
    [("Артём", "думаю, доверие строится на мелочах"),
     ("Алина", "например на том, что ты вернул книгу вовремя"),
     ("Артём", "уже 3 года несу эту книгу как крест"),
     ("Алина", "вот и ред флаг нашли")],
]


def _pick_cast() -> list[dict]:
    """Usually 2 characters, occasionally 3-4 for a group scene. Always
    includes at least one from each model group, so a 2-person scene is
    guaranteed to be two genuinely different models talking, not one model
    voicing both sides."""
    n = random.choices([2, 3, 4], weights=[65, 25, 10])[0]
    females = [p for p in PERSONAS if p["group"] == "f"]
    males = [p for p in PERSONAS if p["group"] == "m"]
    cast = [random.choice(females), random.choice(males)]
    remaining = n - 2
    if remaining > 0:
        pool = [p for p in PERSONAS if p not in cast]
        cast += random.sample(pool, min(remaining, len(pool)))
    random.shuffle(cast)
    return cast


async def _speak(client: httpx.AsyncClient, persona: dict, topic: str, transcript: list[tuple[str, str]]) -> str | None:
    history_text = "\n".join(f"{name}: {line}" for name, line in transcript) or "(разговор ещё не начался)"
    system = f"Ты {persona['name']} — {persona['style']}. {_TURN_RULES}"
    user = f"Тема разговора: {topic}\n\nБеседа пока:\n{history_text}\n\nТвоя следующая реплика:"
    try:
        resp = await client.post(
            "https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": persona["model"],
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
                "max_tokens": _MAX_TOKENS,
                "temperature": 0.9,
            },
        )
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"]
    except Exception as e:
        log.warning("openrouter turn failed for %s (%s): %s", persona["name"], persona["model"], e)
        return None
    content = (content or "").strip().strip('"').strip()
    if content and _FOREIGN_SCRIPT_RE.search(content):
        log.warning("dropping %s's line for foreign-script leak: %r", persona["name"], content)
        return None
    return content or None


async def _generate_via_openrouter(topic: str) -> list[tuple[str, str]] | None:
    if not OPENROUTER_API_KEY:
        return None
    cast = _pick_cast()
    total_turns = random.randint(4, 7)
    transcript: list[tuple[str, str]] = []
    async with httpx.AsyncClient(timeout=20) as client:
        last_speaker = None
        for _ in range(total_turns):
            candidates = [p for p in cast if p["name"] != last_speaker] or cast
            persona = random.choice(candidates)
            line = await _speak(client, persona, topic, transcript)
            if line is None:
                continue  # skip a failed turn, keep the conversation going
            transcript.append((persona["name"], line))
            last_speaker = persona["name"]
    return transcript if len(transcript) >= 2 else None


def _fallback_dialogue() -> list[tuple[str, str]]:
    return random.choice(_FALLBACK_DIALOGUES)


async def generate_dialogue() -> list[tuple[str, str]]:
    topic = random.choice(TOPICS)
    lines = await _generate_via_openrouter(topic)
    return lines if lines else _fallback_dialogue()


async def post_dialogue(bot: Bot) -> None:
    gid = binding.group_id()
    if not gid:
        return

    activity = await cache.get_real_activity(gid)
    if activity >= DIALOGUE_ACTIVITY_THRESHOLD:
        log.info("group has real activity (%d) — skipping AI banter", activity)
        return

    lines = await generate_dialogue()
    cast_names = ", ".join(dict.fromkeys(name for name, _ in lines))  # unique, ordered
    body = "\n".join(f"{speaker}: {text}" for speaker, text in lines)
    message = f"🎭 {cast_names} обсуждают:\n\n{body}\n\nа у тебя как? → @{BOT_USERNAME}"
    try:
        await bot.send_message(int(gid), message)
    except Exception as e:
        log.warning("dialogue post failed: %s", e)
